steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hellokube:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/hellokube:latest', './']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hellokube:latest']
images:
- 'gcr.io/$PROJECT_ID/hellokube:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/hellokube:latest'
